Adjusts the location placed on path and added a test to confirm unpacked binary

diff --git a/.github/workflows/assert-test.yaml b/.github/workflows/assert-test.yaml
--- a/.github/workflows/assert-test.yaml
+++ b/.github/workflows/assert-test.yaml
@@ -41,8 +41,15 @@ jobs:
       - name: Assert the Download
         run: |
           ls -al "$GITHUB_WORKSPACE/bin"
-          ls -al bin
           if [ ! -f "$GITHUB_WORKSPACE/bin/terrahelp_0.7.5_linux_amd64.tar.gz" ]; then
             echo "Assertion failed. File not found in bin"
+            exit 1
+          fi
+      - name: Assert the binary output
+        run: |
+          expected="terrahelp version 0.7.5"
+          binary_output=$(terrahelp --version)
+          if [ "binary_output" != "$expected" ]; then
+            echo "Assertion failed. Expected: $expected, Got: binary_output"
             exit 1
           fi
