Adds an additional step to the assert-test worflow

diff --git a/.github/workflows/assert-test.yaml b/.github/workflows/assert-test.yaml
--- a/.github/workflows/assert-test.yaml
+++ b/.github/workflows/assert-test.yaml
@@ -38,4 +38,9 @@ jobs:
             echo "Assertion failed. Expected: $expected, Got: $output"
             exit 1
           fi
-          ls -al bin
+      - name: Assert the Download
+        run: |
+          if [ ! -f "bin/terrahelp_0.7.5_linux_amd64.tar.gz" ]; then
+            echo "Assertion failed. File not found in bin"
+            exit 1
+          fi
